import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import ThemeWrapper from "@/app/components/wrapper/ThemeWrapper"
import NextAuthProvider from "@/app/components/wrapper/NextAuthProvider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NextAuthProvider>
                    <ThemeWrapper enableSystem={false} attribute="class">
                        {children}
                    </ThemeWrapper>
                </NextAuthProvider>
            </body>
        </html>
    )
}
